apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: express-backend:v1
        imagePullPolicy: Never  # Quan trọng khi sử dụng local image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  selector:
    app: express-backend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP